FROM mcr.microsoft.com/devcontainers/go:0-1.19-bullseye

# copy the generated bundle
ADD nscacert_combined.pem /usr/local/share/ca-certificates/my-cert.crt

# update the ca trust for the image
RUN update-ca-certificates
RUN apt-get update && apt-get install -y ca-certificates openssl git curl && \
    rm -rf /var/lib/apt/lists/* && \
    curl -s https://api.github.com/repos/gohugoio/hugo/releases/latest

RUN git clone https://github.com/dapr/dapr --depth=1 && \
    ls -al